### ISSUE TITLE
etherlime test error

### ISSUE THREAD

**Issue by javaadpatel** [LimeChain/etherlime-shape-react#1]
Hi,

I think the repository might not be up to date because running "etherlime test" results in an error cannot find module "../build/LimeFactory.json". Could this be because there is no LimeFactory.sol file in the contacts folder?

This is the full error output:
`{ Error: Cannot find module '../build/LimeFactory.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Javaad\Documents\BlockChain\ETHHackathon\EtherlimeReact\test\exampleTest.js:3:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\mocha\lib\mocha.js:576:10)
    at Promise (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\cli-commands\etherlime-test\etherlime-test.js:47:9)
    at new Promise (<anonymous>)
    at runMocha (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\cli-commands\etherlime-test\etherlime-test.js:46:9)
    at Object.run (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\cli-commands\etherlime-test\etherlime-test.js:32:8)
    at <anonymous> code: 'MODULE_NOT_FOUND' }`

**Comment by Perseverance** [comment]
Hey, you are right, we've broken the tests. I will commit a change in the test folder in the next minutes and you can replace your test files with the ones there.

**Comment by Perseverance** [comment]
@javaadpatel the tests are fixed, you can replace the tests with the ones in this repo or start a new etherlime shape :) Thank you for your support!

**Comment by javaadpatel** [comment]
That was really quick, everything is working now. Thanks for the help and awesome library.
